Repository agiledev-students-fall2022/final-project-team-resow, pull requests merged in 2022-10, with the labels that each got.

#5 Doc: Update README & CONTRIBUTING file
  CONTRIBUTING.md
  README.md
Labels: documentation

#6 Documentation: add wireframe and app map
  ux-design/Minwu's_Wireframe.drawio
  ux-design/Minwu_AppMap.drawio
Labels: documentation

#44 add starting instructions to Contributing.md
  CONTRIBUTING.md
Labels: documentation

#45 move stuff into components and static respectively
  front-end/src/App.js
  front-end/src/components/Footer.css
  front-end/src/components/Footer.js
  front-end/src/components/Header.css
  front-end/src/components/Header.js
  front-end/src/index.js
  front-end/src/static/logo.svg
  front-end/src/static/resowLogo.png
Labels: refactor

#49 fix image size - card media behaves really weirdly
  front-end/src/components/Message.js
  front-end/src/components/Post.js
Labels: bug

#50 Added new pages for page router
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.js
  front-end/src/components/Footer.js
  front-end/src/index.js
  front-end/src/pages/ChatPage.js
  front-end/src/pages/EditProfile.js
  front-end/src/pages/Homepage.js
  front-end/src/pages/ItemDetails.js
  front-end/src/pages/ItemsList.js
  front-end/src/pages/Messages.js
  front-end/src/pages/PastUpload.js
  front-end/src/pages/SavedPost.js
  front-end/src/pages/SignIn.js
  front-end/src/pages/SignUp.js
  front-end/src/pages/UploadItem.js
  front-end/src/pages/UserProfile.js
  package-lock.json
  package.json
Labels: important, Issue

#64 Search bar
  front-end/src/App.js
  front-end/src/components/SearchBar.js
Labels: Component

#70 69-refactor item detail page
  front-end/package-lock.json
  front-end/package.json
  front-end/public/index.html
  front-end/src/App.js
  front-end/src/components/carousel/ImgCarousel.css
  front-end/src/components/carousel/ImgCarousel.js
  front-end/src/pages/ItemDetails.js
  package-lock.json
  package.json
Labels: refactor

#76 73-user-profile-page-mock-api
  front-end/src/App.js
  front-end/src/pages/UserProfile.js
Labels: front-end page, page

#74 Sign in page/register page
  front-end/src/App.js
  front-end/src/pages/Register.js
  front-end/src/pages/SignIn.js
  front-end/src/pages/SignUp.js
  front-end/src/pages/UploadItem.js
  front-end/src/pages/UserProfile.js
Labels: page

#66 Create upload item page
  front-end/src/pages/UploadItem.js
Labels: page

#92 fix bugs
  front-end/src/App.js
  front-end/src/components/Footer.js
  front-end/src/components/Post.js
  front-end/src/pages/ItemsList.js
Labels: bug, refactor

#90 Upload item page - Image uploading
  front-end/src/components/carousel/ImgCarousel.js
  front-end/src/pages/UploadItem.js
Labels: page

#94 change color of the margin box
  front-end/src/components/Footer.js
Labels: refactor

#97 Fix formatting and edge of white
  front-end/src/pages/Register.js
  front-end/src/pages/SignIn.js
Labels: page

#98 map stuff is pretty much finished. I am happy with this.
  front-end/package-lock.json
  front-end/package.json
  front-end/public/samplefeatures
  front-end/src/components/Map.js
  front-end/src/components/PreviewWindow.js
  front-end/src/pages/Homepage.js
Labels: Component, front-end page

#102 fixed issue with popup rendering before click
  front-end/src/components/Map.js
Labels: bug

#107 refactor user profile
  front-end/src/components/Post.js
  front-end/src/pages/UserProfile.css
Labels: refactor

#123 Add initial backend setup
  back-end/.gitignore
  back-end/app.js
  back-end/package-lock.json
  back-end/package.json
  back-end/server.js
Labels: back-end

#124 create save & delete button
  front-end/src/pages/ItemDetails.js
Labels: refactor, front-end page
